### ISSUE TITLE
Executor exception does not get returned in JUnit tests.

### ISSUE THREAD

**Issue by GCHQDev404** [gchq/Maestro#20]
See Branch: develop-GCHQDev404 commit: 0312911e test: AddExecutorHandlerTest
Note: Handler test passes, but the execute test fails.
The execute test does not throw a unsupported operation exception it lost/hidden, when executor in the test is incorrectly missing the needed handler.

**Comment by GCHQDev404** [comment]
Can you push change to develop, if/when required.

**Comment by m55624** [comment]
Merged into develop.
